-- MySQL Script generated by MySQL Workbench
-- Sun 16 Oct 2016 19:45:26 BST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema k1333307db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema k1333307db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `k1333307db` DEFAULT CHARACTER SET latin1 ;
USE `k1333307db` ;

-- -----------------------------------------------------
-- Table `k1333307db`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`employee` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `sex` CHAR(1) NOT NULL,
  `dateOfBirth` DATE NULL DEFAULT NULL,
  `email` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `k1333307db`.`limbs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`limbs` (
  `thing` VARCHAR(20) NULL DEFAULT NULL,
  `legs` INT(11) NULL DEFAULT NULL,
  `arms` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `k1333307db`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creatorId` INT NOT NULL,
  `type` ENUM('Social', 'Business') NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `date` DATE NOT NULL,
  `time` TIME NOT NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `_idx` (`creatorId` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`creatorId`)
    REFERENCES `k1333307db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k1333307db`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `creatorID` INT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `_idx` (`creatorID` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`creatorID`)
    REFERENCES `k1333307db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k1333307db`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`comment` (
  `id` INT NOT NULL,
  `creatorId` INT NOT NULL,
  `statusId` INT NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_1_idx` (`creatorId` ASC),
  INDEX `fk_comment_2_idx` (`statusId` ASC),
  CONSTRAINT `fk_comment_1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `k1333307db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_2`
    FOREIGN KEY (`statusId`)
    REFERENCES `k1333307db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k1333307db`.`likeStatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`likeStatus` (
  `employeeId` INT NOT NULL,
  `statusId` INT NOT NULL,
  PRIMARY KEY (`employeeId`, `statusId`),
  INDEX `fk_likeStatus_1_idx` (`statusId` ASC),
  CONSTRAINT `fk_likeStatus_1`
    FOREIGN KEY (`statusId`)
    REFERENCES `k1333307db`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likeStatus_2`
    FOREIGN KEY (`employeeId`)
    REFERENCES `k1333307db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `k1333307db`.`likeComment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `k1333307db`.`likeComment` (
  `employeeId` INT NOT NULL,
  `commentId` INT NOT NULL,
  PRIMARY KEY (`employeeId`, `commentId`),
  INDEX `fk_likeComment_1_idx` (`commentId` ASC),
  CONSTRAINT `fk_likeComment_1`
    FOREIGN KEY (`commentId`)
    REFERENCES `k1333307db`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likeComment_2`
    FOREIGN KEY (`employeeId`)
    REFERENCES `k1333307db`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
